services:
  - type: web
    name: carbon-footprint-tracker
    runtime: node
    buildCommand: |
      echo "Installing dependencies..."
      npm run install-all
      echo "Rebuilding client dependencies..."
      cd client && npm rebuild && npm install vite --save-dev
      echo "Building client..."
      cd client && npm run build
      echo "Build complete!"
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health